Repository crdschurch/crds-net, pull requests merged in 2019-04, with the labels that each got.

#817 06 Deploy
  Gemfile
  Gemfile.lock
  _assets/javascripts/config.js
  _assets/javascripts/vendor/ash-wednesday-experience.js
  _assets/javascripts/vendor/imgix-optimizer.js
  _config.yml
  _includes/_head.html
  _includes/_shared_global_header.html
  _includes/media/_overlay-card.html
  _plugins/filters/html_and_meta_util_filter.rb
  _plugins/filters/media_url_filter.rb
  cypress/Contentful/ContentfulApi.js
  cypress/Contentful/ContentfulElementValidator.js
  cypress/Contentful/Fields/ContentfulField.js
  cypress/Contentful/Fields/DateField.js
  cypress/Contentful/Fields/ImageField.js
  cypress/Contentful/Fields/TextField.js
  cypress/Contentful/ImageDisplayValidator.js
  cypress/Contentful/Models/LocationModel.js
  cypress/Contentful/Models/MessageModel.js
  cypress/Contentful/Models/PromoModel.js
  cypress/Contentful/Models/RedirectModel.js
  cypress/Contentful/Models/SeriesModel.js
  cypress/Contentful/QueryManagers/LocationQueryManager.js
  cypress/Contentful/QueryManagers/MessageQueryManager.js
  cypress/Contentful/QueryManagers/PromoQueryManager.js
  cypress/Contentful/QueryManagers/RedirectQueryManager.js
  cypress/Contentful/QueryManagers/SeriesQueryManager.js
  cypress/README.md
  cypress/integration/external_repo_media/current_series_page_spec.js
  cypress/integration/external_repo_media/landing_page_current_series_spec.js
  cypress/integration/external_repo_media/series_page_current_series_spec.js
  cypress/integration/homepage/home_page_current_series_spec.js
  cypress/integration/homepage/home_page_happenings_spec.js
  cypress/integration/homepage/home_page_latest_message_spec.js
  cypress/integration/infrastructure/redirect_regression_spec.js
  cypress/integration/live/live_current_series_spec.js
  cypress/integration/live/live_latest_message_spec.js
  cypress/integration/locations/locations_current_series_spec.js
  cypress/integration/locations/locations_search_spec.js
  cypress/integration/sharedHeader/crossroads_logo_redirect_authspec.js
  cypress/integration/sharedHeader/crossroads_logo_redirect_spec.js
  cypress/integration/sharedHeader/media_dropdown_current_series_spec.js
  cypress/integration/sharedHeader/profile_dropdown_link_authspec.js
  cypress/integration/sharedHeader/sign_in_and_out_authspec.js
  cypress/kickOffCypress.sh
  cypress/plugins/index.js
  cypress/support/Formatter.js
  cypress/support/commands.js
  index.html
  lib/utils/meta_util.rb
  package-lock.json
  package.json
  redirects.csv
  spec/unit/meta_util_spec.rb
Labels: DO NOT MERGE

#832 [SPIKE] JWT Auth
  admin.html
  auth-fail.html
  redirects.csv
Labels: DO NOT MERGE

#861 [hotfix] Community Store (Demo)
  _assets/stylesheets/pages/_community-store.scss
  _assets/stylesheets/pages/_modules.scss
Labels: DO NOT MERGE, HOTFIX

#860 [hotfix] Community Store (Production)
  _assets/stylesheets/pages/_community-store.scss
  _assets/stylesheets/pages/_modules.scss
Labels: DO NOT MERGE, HOTFIX, Production
